name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7, "3.0", 3.1, head]
        jekyll: ["~> 4.0", "~> 3.0"]
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
    env:
      JEKYLL_VERSION: ${{ matrix.jekyll }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: "Install dependencies (Jekyll: ${{matrix.jekyll}})"
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
